### PR TITLE
User Authentication

### PR DESCRIPTION
**Pull request by 9gix**
- [x] User Login
- [x] User Sign Up
- [x] account activation (via email)
- [x] ~~forget password~~ (NOT Implemented)

### CODE REVIEW

**Comment by 9gix** [comment]
3rd party apps installed. Don't forget to do the standard procedure of setup:
- install requirements
- run migration

**Comment by digawp** [comment]
How is the Views being managed in this app? Is it done by `registration.backends.default.urls`?

**Comment by 9gix** [comment]
https://docs.djangoproject.com/en/1.8/topics/auth/default/#all-authentication-views
https://github.com/django/django/blob/master/django/contrib/auth/views.py

`django.contrib.auth.views`

**Comment by digawp** [comment]
We'll update the view to use bootstrap if we have time later (not core feature)

**Pull request merged**
