### PR TITLE
Feature/seed

### PR DESCRIPTION
**Pull request by jkt001**
Update current data seeds to reflect real world data, remove "-" from person and seeded new information to already available seeds

one important info: I falsely dumped the data into the root folder instead of the <app>/fixture/<app>_data.json...

this has been fixed

### CODE REVIEW

**Comment by jkt001** [comment]
Ready to merge: better to merge this ASAP since I have previously dumped the data to the wrong location (when I moved organisation to multimedia).

**Comment by digawp** [comment]
Is this based on the latest master? Because Eugene has already fixed the duplicate fixtures at the project directory

**Comment by 9gix** [comment]
I will close this PR. 
- This branch is outdated.
- I already removed those files where you wrongly dump them into the project directory and commit them.
- Renaming "asdf" to "Frozen OST..." should only its portion, not redumping the whole seed data. https://github.com/exclusive-gix/cs2102-store/commit/9782ef4db903785f969918e23a40badeef5e1b43
- This Commit is not very clear: https://github.com/exclusive-gix/cs2102-store/commit/e40b0f3d770b030c8ebdb18cc875444ae7c47d13

**Comment by 9gix** [comment]
@digawp @jkt001 I will also delete this branch as it contains a commit which shouldn't be merged to master later. Any objection?

**Comment by jkt001** [comment]
ini contain fixes ke existing data;
contoh: buku CLRS publisher Music Industry -> diganti jadi MIT Press, added author data

like gw kerjain ini kmrn di airport smbil tunggu boarding krn like ini tedious work... dan sesuatu yg gw rasa ga berat buat dikerjain smbil nunggu...

gw minta maaf aja commit nya jd 1 semua gitu, jd bingung review nya...

ini all existing data itu dibenerin publisher, author, singer, dll... agak aneh kl buku semua publisher (sblm gw ubah) itu Music Industry semua...

**Comment by digawp** [comment]
Jek ini kalo di merge ke master ada kemungkinan kacau lagi, soalnya ada kemungkinan seed lu udh outdated.
Lu perlu merge master ke branch ini, terus coba migrate and see if everything is still correct.
Let us know if everything is still correct after migrate. Kalo iya, kita bisa merge. Otherwise, mending kita fix datanya belakangan aja. Menurut gw sih ga worth it maintaining data when it is a database project.

**Comment by jkt001** [comment]
ud gw fix dulu... didn't i say it yesterday kl gw bakal benerin existing datanya sambil nunggu di airport... nvm... gw yg salah... maaf... gw benerin dulu ini...

small things also matter, tbh...

**Comment by jkt001** [comment]
new PR created (see #47 )

**Comment by digawp** [comment]
Ini bukan soal important or not important. Ini ga urgent dan malah hinder our progress. Actually creating view does not depend on the correctness of the seed.

**Comment by jkt001** [comment]
ud beres diga.... liat PR #47 

gw lg bikin app_view skrg

**Pull request closed without merging**
